from typing import Any, Dict, Optional

def push_url(url: str) -> Any: ...
def redirect(url: str) -> Any: ...
def trigger_event(event_name: str, params: Optional[Dict[str, Any]] = None) -> Any: ...
def reload(
    template_name: Optional[str] = None, context: Optional[Dict[str, Any]] = None
) -> Any: ...
