#!/usr/bin/env python3.9
import atexit
import os
import readline

# Enable tab completion
readline.parse_and_bind("tab: complete")

# History file
histfile = os.path.join(os.environ["HOME"], ".python_history")
try:
    readline.read_history_file(histfile)
except FileNotFoundError:
    pass

atexit.register(readline.write_history_file, histfile)
