# Stub file for users.templatetags.user_tags
from django import template

register = template.Library()

def full_name_or_username(user): ...
def profile_image_url(user): ...
def user_role(user): ...
def auth_user_display(user): ...
def auth_status_badge(user): ...
def has_verified_email(user): ...
def login_url_with_next(context): ...
