# Stub file for core.commons
from typing import Any, Dict

from django.http import HttpRequest

def get_active_namespace(request: HttpRequest) -> str: ...
def get_user_display_name(user: Any) -> str: ...
def get_app_settings() -> Dict[str, Any]: ...
