# Stub file for core.mixins
from typing import TypeVar

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import ContextMixin

ContextView = TypeVar("ContextView", bound=ContextMixin)

class BreadcrumbMixin(ContextMixin): ...
class PageTitleMixin(ContextMixin): ...
class SectionMixin(ContextMixin): ...
class ViewMixin(BreadcrumbMixin, PageTitleMixin, SectionMixin): ...
class AuthViewMixin(LoginRequiredMixin, ViewMixin): ...
