# Stub file for responsibility.templatetags.responsibility_tags
from django import template

register = template.Library()

def user_has_responsibility(user, obligation): ...
def user_responsibility_roles(user, obligation): ...
def format_responsibility_roles(roles): ...
def get_responsible_users(obligation): ...
