# Generated by Django 5.1.5 on 2025-02-05 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_completed", models.BooleanField(default=True)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[("bar", "Bar Chart"), ("pie", "Pie Chart")],
                        default="bar",
                        max_length=20,
                    ),
                ),
                ("refresh_interval", models.IntegerField(default=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Preference",
                "verbose_name_plural": "Dashboard Preferences",
            },
        ),
    ]
