# Generated by Django 5.1.5 on 2025-02-05 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardpreference",
            name="chart_type",
            field=models.CharField(
                choices=[("bar", "Bar"), ("line", "Line"), ("pie", "Pie")],
                default="bar",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dashboardpreference",
            name="refresh_interval",
            field=models.PositiveIntegerField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(
                        10, message="Refresh interval must be at least 10 seconds"
                    ),
                    django.core.validators.MaxValueValidator(
                        300, message="Refresh interval cannot exceed 300 seconds"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dashboardpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
