# Stub file for feedback.views

from django.http import HttpRequest, HttpResponse

def index(request: HttpRequest) -> HttpResponse: ...
def submit_bug_report(request: HttpRequest) -> HttpResponse: ...
def export_report(request: HttpRequest, report_id: int) -> HttpResponse: ...
def import_report(request: HttpRequest) -> HttpResponse: ...
def get_plaintext_template(template_path: str) -> str: ...
def get_status_description(status: str) -> str: ...
