# Stub file for core.utils.roles
from enum import Enum
from typing import Dict, List, Tuple

class ProjectRole(str, Enum): ...

ROLE_DISPLAY_NAMES: Dict[str, str]
ROLE_COLORS: Dict[str, str]

def get_role_display(role_value: str) -> str: ...
def get_role_color(role_value: str) -> str: ...
def get_role_choices() -> List[Tuple[str, str]]: ...
def get_responsibility_choices() -> List[Tuple[str, str]]: ...
def get_role_from_responsibility(responsibility: str) -> str | None: ...
def get_responsibility_from_role(role: str) -> str | None: ...
def get_responsibility_display_name(responsibility: str) -> str: ...
