from typing import Any, Callable, Dict

def hyperscript_tags() -> str: ...
def _() -> Callable[[str], str]: ...
def add_class() -> Callable[[str, str], str]: ...
def remove_class() -> Callable[[str, str], str]: ...
def toggle_class() -> Callable[[str, str], str]: ...
def take_class() -> Callable[[str, str], str]: ...
def settle() -> str: ...
def wait() -> str: ...
def hyperscript() -> Dict[str, Any]: ...
